import type { TransactionRow } from "./types";

export const mockTransactions: TransactionRow[] = [
  {
    id_transaccion: 1001,
    fec_tra: "2026-06-10",
    cliente: 12345,
    compania: 1,
    ramo: 10,
    secuencial: 100001,
    monto: 50000,
    estado: "APROBADO",
    codigo_rechazo: null,
    descripcion_rechazo: null,
    respuesta_banco: "00",
    oficial: 501,
    gerente: 10,
    intermediario: 5,
    nombre_oficial: "Juan Perez",
    nombre_gerente: "Carlos Lopez",
    nombre_intermediario: "Intermediarios XYZ",
    seleccion: "N"
  },
  {
    id_transaccion: 1002,
    fec_tra: "2026-06-11",
    cliente: 12346,
    compania: 1,
    ramo: 10,
    secuencial: 100002,
    monto: 75000,
    estado: "RECHAZADO",
    codigo_rechazo: "R001",
    descripcion_rechazo: "Fondos insuficientes",
    respuesta_banco: "05",
    oficial: 502,
    gerente: 11,
    intermediario: 6,
    nombre_oficial: "Maria Garcia",
    nombre_gerente: "Patricia Ruiz",
    nombre_intermediario: "Grupo ABC",
    seleccion: "N"
  },
  {
    id_transaccion: 1003,
    fec_tra: "2026-06-11",
    cliente: 12347,
    compania: 2,
    ramo: 20,
    secuencial: 200001,
    monto: 100000,
    estado: "DECLINADO",
    codigo_rechazo: "D001",
    descripcion_rechazo: "Tarjeta suspendida",
    respuesta_banco: "91",
    oficial: 501,
    gerente: 10,
    intermediario: 5,
    nombre_oficial: "Juan Perez",
    nombre_gerente: "Carlos Lopez",
    nombre_intermediario: "Intermediarios XYZ",
    seleccion: "N"
  },
  {
    id_transaccion: 1004,
    fec_tra: "2026-06-12",
    cliente: 12348,
    compania: 1,
    ramo: 10,
    secuencial: 100003,
    monto: 25000,
    estado: "APROBADO",
    codigo_rechazo: null,
    descripcion_rechazo: null,
    respuesta_banco: "00",
    oficial: 503,
    gerente: 12,
    intermediario: 7,
    nombre_oficial: "Luis Martinez",
    nombre_gerente: "Diana Fernandez",
    nombre_intermediario: "Partners DEF",
    seleccion: "N"
  },
  {
    id_transaccion: 1005,
    fec_tra: "2026-06-12",
    cliente: 12349,
    compania: 2,
    ramo: 20,
    secuencial: 200002,
    monto: 150000,
    estado: "APROBADO",
    codigo_rechazo: null,
    descripcion_rechazo: null,
    respuesta_banco: "00",
    oficial: 504,
    gerente: 13,
    intermediario: 8,
    nombre_oficial: "Rosa Sanchez",
    nombre_gerente: "Miguel Angel",
    nombre_intermediario: "Intermediarios GHI",
    seleccion: "N"
  }
];
