-- PROGRAM UNIT: F_FREC_CONS_TEMP_SUMA
-- Tipo: Function
-- ====================================================================

FUNCTION F_FREC_CONS_TEMP_SUMA(P_TIPO_COBERTURA NUMBER,P_FRECUENCIA NUMBER,P_ID NUMBER)  
RETURN NUMBER
IS

CURSOR C_BUSCA_SEC IS
SELECT SUM(NVL(FRECUENCIA,0))
FROM REEMBOLSO.FRECUENCIA_CONSUMIDA_TEMP
WHERE TIPO_COBERTURA=P_TIPO_COBERTURA;

V_FRECUENCIA_ACUM NUMBER;

BEGIN
	
		V_FRECUENCIA_ACUM:=NULL;
		
		OPEN C_BUSCA_SEC;
		FETCH C_BUSCA_SEC INTO V_FRECUENCIA_ACUM;
		CLOSE C_BUSCA_SEC;	
		
	
	RETURN V_FRECUENCIA_ACUM;
	
	
  
END;
