-- PROGRAM UNIT: F_FREC_CONS_TEMP_IN_UP
-- Tipo: Function
-- ====================================================================

FUNCTION F_FREC_CONS_TEMP_IN_UP(P_TIPO_COBERTURA NUMBER,P_FRECUENCIA NUMBER,P_ID NUMBER)  
RETURN NUMBER
IS

CURSOR C_BUSCA_SEC IS
SELECT SEQ_FRECUENCIA_CONSUMIDA_TEMP.NEXTVAL
FROM DUAL;

V_SECUENCIA NUMBER;

BEGIN
	
	IF P_ID IS NULL THEN 
		OPEN C_BUSCA_SEC;
		FETCH C_BUSCA_SEC INTO V_SECUENCIA;
		CLOSE C_BUSCA_SEC;	
		
		INSERT INTO REEMBOLSO.FRECUENCIA_CONSUMIDA_TEMP(TIPO_COBERTURA,FRECUENCIA,ID)  
		VALUES (P_TIPO_COBERTURA,P_FRECUENCIA ,V_SECUENCIA);
		
	ELSE 
			V_SECUENCIA:=P_ID;
		UPDATE REEMBOLSO.FRECUENCIA_CONSUMIDA_TEMP
		SET TIPO_COBERTURA=P_TIPO_COBERTURA,FRECUENCIA=P_FRECUENCIA
		WHERE ID=V_SECUENCIA;
		
	END IF;
	
	RETURN V_SECUENCIA;
	
	
  
END;
