-- PROGRAM UNIT: P_AJUSTA_ESTATUS_SOL_PAG
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_AJUSTA_ESTATUS_SOL_PAG IS
	CURSOR CUR_SOL_PEND IS
		SELECT 1
		FROM SOLICITUD_SERVICIO
		WHERE SOLICITUD_PAGO_ID = :RADICACION.NUMERO_SOLICITUD
		AND ESTATUS IN (PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EST_PEN_SOL_SER_REMB',:GLOBAL.COD_COMPANIA),
                         PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EST_PEN_DOC_SOL_SER',:GLOBAL.COD_COMPANIA));
  V_EXISTE	NUMBER;
BEGIN
  IF :RADICACION.NUMERO_SOLICITUD IS NOT NULL THEN
	  OPEN CUR_SOL_PEND;
	  FETCH CUR_SOL_PEND INTO V_EXISTE;
	  IF CUR_SOL_PEND%NOTFOUND THEN
	  	UPDATE SOLICITUD_PAGO
	  	SET ESTATUS = PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EST_COM_SOL_PAG_REMB',:GLOBAL.COD_COMPANIA)
	  	WHERE ID = :RADICACION.NUMERO_SOLICITUD;
	  	
			:SYSTEM.MESSAGE_LEVEL := '25';
  		COMMIT;	
   		:SYSTEM.MESSAGE_LEVEL := '0';
   		
	  END IF;
	  CLOSE CUR_SOL_PEND;
	END IF;
END;
