-- PROGRAM UNIT: P_ANULA_RECLAMACION
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_ANULA_RECLAMACION(P_SOL_SER_ID	NUMBER) IS
	CURSOR CUR_EXISTE_RECLAMO IS
		SELECT ID
		FROM RECLAMO
		WHERE SOLICITUD_SERVICIO_ID = P_SOL_SER_ID;
		
	V_RECLAMO	RECLAMO.ID%TYPE;
	
BEGIN
  OPEN CUR_EXISTE_RECLAMO;
  FETCH CUR_EXISTE_RECLAMO INTO V_RECLAMO;
  CLOSE CUR_EXISTE_RECLAMO;
  
  IF V_RECLAMO IS NOT NULL THEN
  	UPDATE RECLAMO
  	SET ESTATUS = PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EST_ANU_RECLAMO',:GLOBAL.COD_COMPANIA)
  	WHERE ID = V_RECLAMO;
  	
  	P_BUSCAR_RECLAMO(V_RECLAMO, :GLOBAL.COD_COMPANIA);
  END IF;
END;
