-- PROGRAM UNIT: P_BUSCA_DATOS_CUENTA_BANCARIA
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_BUSCA_DATOS_CUENTA_BANCARIA(P_NUMERO_AFILIADO	NUMBER, P_TIPO_AFILIADO VARCHAR2)  IS
	CURSOR C_DATOS_NUM_CTA IS
		SELECT N.CODIGO, N.TIP_CTA, DECODE(N.TIP_CTA,'A','AHOR','CORR') COD_TIPO_CUENTA, N.NUM_CTA, N.BANCO, N.TIP_PRO, N.FEC_TRA, N.PROPIETARIO, N.CODIGO_IDENTIFICADOR, N.CDPERSON, N.VALIDADA, N.TOKENIZADA, N.USER_TOKENIZA, N.FECHA_TOKENIZA, --N.CANAL,
		       I.CONTRATANTE_NOM, I.CONTRATANTE_CED, I.CONTRATANTE_TIPO_ID, I.COD_NACIONALIDAD, I.TIP_PROPIETARIO, I.SEXO, I.EMAIL_NOTIFICA_PAGO--, I.TELEFONO
		 FROM NUMERO_CUENTA N, NUMERO_CUENTA_INFO I
		WHERE I.CODIGO = N.CODIGO
		 AND N.NUM_CTA =:RADICACION.NUMERO_CUENTA
		 /*AND N.TIP_PRO = P_TIPO_AFILIADO
		 AND N.PROPIETARIO = P_NUMERO_AFILIADO*/ -- OMARLIS GOMEZ Y ANGEL CASTILLO, FOREBRA (05/02/2024). COMENTADO DOS CONDICIONES
		 ORDER BY N.CODIGO DESC;
	
	R_DATOS_NUM_CTA		C_DATOS_NUM_CTA%ROWTYPE;
	
	V_EXISTE_IDENTIFICACION VARCHAR2(1) := 'N';
	
	-- OMARLIS GOMEZ Y ANGEL CASTILLO, FOREBRA (05/02/2024). CURSOR PARA VALIDAR SI EXISTE LA CEDULA
	CURSOR CUR_BUSCA_CEDULA(P_CEDULA VARCHAR2) IS
		SELECT 'S'
		  FROM ASEGURADO
		WHERE CODIGO  = P_NUMERO_AFILIADO
		  AND CED_ACT = P_CEDULA
		  AND ESTATUS = 5
		UNION
		SELECT 'S'
		  FROM DEPENDIENTE
		WHERE ASEGURADO = P_NUMERO_AFILIADO
		  AND CED_ACT   = P_CEDULA
		  AND ESTATUS   = 23;
	
	-- OMARLIS GOMEZ Y ANGEL CASTILLO, FOREBRA (05/02/2024). CURSOR PARA VALIDAR SI EXISTE EL PASAPORTE
	CURSOR CUR_BUSCA_PASAPORTE(P_PASAPORTE VARCHAR2) IS
		SELECT 'S'
		  FROM ASEGURADO
		WHERE CODIGO    = P_NUMERO_AFILIADO
		  AND PASAPORTE = P_PASAPORTE
		  AND ESTATUS   = 5
		UNION
		SELECT 'S'
		  FROM DEPENDIENTE
		WHERE ASEGURADO = P_NUMERO_AFILIADO
		  AND PASAPORTE = P_PASAPORTE
		  AND ESTATUS   = 23;	  

BEGIN

	-- OMARLIS GOMEZ Y ANGEL CASTILLO, FOREBRA (05/02/2024). MODIFICACION DEL CODIGO 
  FOR R_DATOS_NUM_CTA IN  C_DATOS_NUM_CTA LOOP
  	
  /*	V_EXISTE_IDENTIFICACION := 'N';
  	  
		IF R_DATOS_NUM_CTA.CONTRATANTE_TIPO_ID = 'C' THEN
			OPEN  CUR_BUSCA_CEDULA(R_DATOS_NUM_CTA.CONTRATANTE_CED);
			FETCH CUR_BUSCA_CEDULA INTO V_EXISTE_IDENTIFICACION;
			CLOSE CUR_BUSCA_CEDULA;
		ELSIF R_DATOS_NUM_CTA.CONTRATANTE_TIPO_ID = 'P' THEN	
			OPEN  CUR_BUSCA_PASAPORTE(R_DATOS_NUM_CTA.CONTRATANTE_CED);
			FETCH CUR_BUSCA_PASAPORTE INTO V_EXISTE_IDENTIFICACION;
			CLOSE CUR_BUSCA_PASAPORTE;
		END IF;
		*/
	--	IF V_EXISTE_IDENTIFICACION = 'S' THEN
			--:RADICACION.TIPO_CUENTA        := R_DATOS_NUM_CTA.COD_TIPO_CUENTA; --Tommy Pereyra Enfoco 15/10/2024
		  :RADICACION.NOMBRE_PROPIETARIO := R_DATOS_NUM_CTA.CONTRATANTE_NOM;
		  :RADICACION.TIPO_PROPIETARIO   := R_DATOS_NUM_CTA.TIP_PROPIETARIO;
		  --:RADICACION.NUMERO_DOCUMENTO   := R_DATOS_NUM_CTA.CONTRATANTE_CED; --Tommy Pereyra Enfoco 15/10/2024
		  --:RADICACION.TIPO_DOCUMENTO     := R_DATOS_NUM_CTA.CONTRATANTE_TIPO_ID; --Tommy Pereyra Enfoco 15/10/2024
		  :RADICACION.SEXO               := R_DATOS_NUM_CTA.SEXO;
		  :RADICACION.NACIONALIDAD       := R_DATOS_NUM_CTA.COD_NACIONALIDAD;
		  :RADICACION.CORREO_PROPIETARIO := R_DATOS_NUM_CTA.EMAIL_NOTIFICA_PAGO;
		  
		  EXIT;
	--	END IF;	
	
  END LOOP;
  
END;
