-- PROGRAM UNIT: P_BUSCA_CORREO_AFILIADO
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_BUSCA_CORREO_AFILIADO(P_NUMERO_AFILIADO	NUMBER, P_TIPO_AFILIADO	VARCHAR2) IS
	V_TIPO_CLIENTE VARCHAR2(100);
	V_NOMBRE_CLIENTE VARCHAR2(1000);
BEGIN
	
  :RADICACION.CORREO_NOTIFICA := F_buscar_cliente_correo (P_NUMERO_AFILIADO, P_TIPO_AFILIADO);
END;
