-- PROGRAM UNIT: P_CARGA_RESUMEN_RECLAMOS
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_CARGA_RESUMEN_RECLAMOS IS
	CURSOR CUR_MONTO_TOTALES IS
		SELECT SUM(CS.MONTO_RECLAMADO), SUM(CS.MONTO_COBERTURA)
		FROM COBERTURA_SOLICITADA CS, SOLICITUD_SERVICIO SS
		WHERE CS.SOLICITUD_SERVICIO_ID = SS.ID
		AND SS.SOLICITUD_PAGO_ID = :RADICACION.NUMERO_SOLICITUD;
		
	CURSOR CUR_CODIGO_PAGO IS
		SELECT SOLICITUD_PAGO_ID
		FROM SOLICITUD_PAGO
		WHERE ID = :RADICACION.NUMERO_SOLICITUD;
		
BEGIN

	  OPEN CUR_MONTO_TOTALES;
	  FETCH CUR_MONTO_TOTALES INTO :CG$CTRL.TOTAL_RECLAMO ,:CG$CTRL.TOTAL_PAGAR;
	  CLOSE CUR_MONTO_TOTALES;
	  
	  OPEN CUR_CODIGO_PAGO;
	  FETCH CUR_CODIGO_PAGO INTO :CG$CTRL.CODIGO_PAGO;
	  CLOSE CUR_CODIGO_PAGO;
	  
	  GO_BLOCK('RESUMEN_RECLAMOS');
	  EXECUTE_QUERY;
END;
