-- PROGRAM UNIT: P_CARGA_SOLICITUD_PAGO
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_CARGA_SOLICITUD_PAGO IS

  CURSOR CUR_SOLICITUD_PAGO IS
      SELECT SP.BENEFICIARIO_ID
          FROM SOLICITUD_PAGO SP
         WHERE SP.ID = :PARAMETER.P_SOLICITUD_PAGO; 
  
BEGIN
		
	IF :PARAMETER.P_SOLICITUD_PAGO IS NOT NULL THEN
		Set_Block_Property('RADICACION',default_where, 'ID = '||:PARAMETER.P_SOLICITUD_PAGO);
		Set_Block_Property('SOLICITUD_SERVICIO',default_where, 'ID IS NULL');
				
		
		OPEN CUR_SOLICITUD_PAGO;
		FETCH CUR_SOLICITUD_PAGO INTO :CG$CTRL.NO_AFI;
		CLOSE CUR_SOLICITUD_PAGO;
				
		P_BUSCA_DATOS_AFILIADO;
		:CG$CTRL.SOLICITUD_EXISTENTE := :PARAMETER.P_SOLICITUD_PAGO;
		
		P_LLENA_TABLAS_TEMPORALES_TABS;
		
		GO_BLOCK('RADICACION');
		CLEAR_BLOCK(NO_VALIDATE);
		EXECUTE_QUERY;
		-- OMARLIS GOMEZ Y LUIS CALCAÑO, FOREBRA (31/01/2024). COMENTADO
		/*IF :RADICACION.ESTATUS = PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EST_COM_SOL_PAG_REMB',:GLOBAL.COD_COMPANIA) THEN
			SET_ITEM_PROPERTY('RESUMEN_RECLAMOS.BTN_EDITAR', ENABLED, PROPERTY_FALSE);
		END IF;*/ 
		
		GO_BLOCK('RESUMEN_RECLAMOS');
		
	END IF;
	
END;
