-- PROGRAM UNIT: P_HABILITA_BLOCK_EXGRATIA
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_HABILITA_BLOCK_EXGRATIA(P_ESTATUS NUMBER, P_BLOQUE VARCHAR2) IS
  --
  v_pendient_spool  NUMBER(5) := F_OBTEN_PARAMETRO_SEUS('SOL_PAG_REEMB.EST_PS', :GLOBAL.COD_COMPANIA);
  --
BEGIN
  IF P_ESTATUS = v_pendient_spool THEN
     IF P_BLOQUE = 'RADICACION' THEN 
        SET_BLOCK_PROPERTY(P_BLOQUE, UPDATE_ALLOWED, PROPERTY_FALSE);
     ELSE
        SET_BLOCK_PROPERTY(P_BLOQUE, UPDATE_ALLOWED, PROPERTY_FALSE);
        SET_BLOCK_PROPERTY(P_BLOQUE, INSERT_ALLOWED, PROPERTY_FALSE);
     END IF;
  ELSE
     IF P_BLOQUE = 'RADICACION' THEN 
        SET_BLOCK_PROPERTY(P_BLOQUE, UPDATE_ALLOWED, PROPERTY_TRUE);
     ELSE
        SET_BLOCK_PROPERTY(P_BLOQUE, UPDATE_ALLOWED, PROPERTY_TRUE);
        SET_BLOCK_PROPERTY(P_BLOQUE, INSERT_ALLOWED, PROPERTY_TRUE);
     END IF;
  END IF;
  /*
  IF P_ESTATUS = v_pendient_spool THEN
     IF P_BLOQUE = 'RADICACION' THEN 
        SET_BLOCK_PROPERTY(P_BLOQUE, UPDATE_ALLOWED, PROPERTY_FALSE);
     ELSE
        SET_BLOCK_PROPERTY('SOLICITUD_PAGO_DETALLE', UPDATE_ALLOWED, PROPERTY_FALSE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', UPDATE_ALLOWED, PROPERTY_FALSE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', UPDATE_ALLOWED, PROPERTY_FALSE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', UPDATE_ALLOWED, PROPERTY_FALSE);
        --
        SET_BLOCK_PROPERTY('SOLICITUD_PAGO_DETALLE', INSERT_ALLOWED, PROPERTY_FALSE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', INSERT_ALLOWED, PROPERTY_FALSE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', INSERT_ALLOWED, PROPERTY_FALSE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', INSERT_ALLOWED, PROPERTY_FALSE);
     END IF;
  ELSE
     IF P_BLOQUE = 'RADICACION' THEN 
        SET_BLOCK_PROPERTY(P_BLOQUE, UPDATE_ALLOWED, PROPERTY_TRUE);
     ELSE
        SET_BLOCK_PROPERTY('SOLICITUD_PAGO_DETALLE', UPDATE_ALLOWED, PROPERTY_TRUE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', UPDATE_ALLOWED, PROPERTY_TRUE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', UPDATE_ALLOWED, PROPERTY_TRUE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', UPDATE_ALLOWED, PROPERTY_TRUE);
        --
        SET_BLOCK_PROPERTY('SOLICITUD_PAGO_DETALLE', INSERT_ALLOWED, PROPERTY_TRUE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', INSERT_ALLOWED, PROPERTY_TRUE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', INSERT_ALLOWED, PROPERTY_TRUE);
        SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', INSERT_ALLOWED, PROPERTY_TRUE);
     END IF;
  END IF;*/
END;
