-- PROGRAM UNIT: P_HABILITA_BLOQ_SERV
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_HABILITA_BLOQ_SERV(P_HABILITA BOOLEAN) IS
BEGIN
  IF P_HABILITA THEN
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO', UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('BUSCA_SERVICIO', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_BLOCK_PROPERTY('BUSCA_SERVICIO', UPDATE_ALLOWED, PROPERTY_TRUE);
  	--SET_ITEM_PROPERTY('CG$CTRL.BTN_AGREGAR_DATOS_SERV', ENABLED, PROPERTY_TRUE);
  --	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_EDITAR_COB', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_EDITAR_MON', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_BORRAR', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_COBR_INDE', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_EXCEPCION_NEGOCIO', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_TARIFA_INCORECTA', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_NEGOCIACION_PRESTADOR', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('CG$CTRL.CHK_FUERA_COB', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('CG$CTRL.CHK_FUERA_COB', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('CG$CTRL.CHK_FUERA_COB', UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.MONTO_NO_CUB', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.MONTO_NO_CUB', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.MONTO_NO_CUB', UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.DESCRIPCION_NO_CUB', ENABLED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.DESCRIPCION_NO_CUB', INSERT_ALLOWED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.DESCRIPCION_NO_CUB', UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_ITEM_PROPERTY('BUSCA_SERVICIO.LOV_PRESTADOR_ADD', ENABLED, PROPERTY_TRUE);
  ELSE
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO', INSERT_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO', UPDATE_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', INSERT_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_MOT', UPDATE_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', INSERT_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERV_DIAG', UPDATE_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', INSERT_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('SOLICITUD_SERVICIO_DETALLE', UPDATE_ALLOWED, PROPERTY_FALSE); 
  	SET_BLOCK_PROPERTY('BUSCA_SERVICIO', INSERT_ALLOWED, PROPERTY_FALSE);
  	SET_BLOCK_PROPERTY('BUSCA_SERVICIO', UPDATE_ALLOWED, PROPERTY_FALSE);
  	--SET_ITEM_PROPERTY('CG$CTRL.BTN_AGREGAR_DATOS_SERV', ENABLED, PROPERTY_FALSE); 
  ---	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_EDITAR_COB', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_EDITAR_MON', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_BORRAR', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_COBR_INDE', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_EXCEPCION_NEGOCIO', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_TARIFA_INCORECTA', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO_DETALLE.BTN_NEGOCIACION_PRESTADOR', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('CG$CTRL.CHK_FUERA_COB', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.MONTO_NO_CUB', ENABLED, PROPERTY_FALSE);
  	SET_ITEM_PROPERTY('SOLICITUD_SERVICIO.DESCRIPCION_NO_CUB', ENABLED, PROPERTY_FALSE);  	
  	SET_ITEM_PROPERTY('BUSCA_SERVICIO.LOV_PRESTADOR_ADD', ENABLED, PROPERTY_FALSE);	
  END IF;
END;
