-- PROGRAM UNIT: P_INSERTA_EN_RECL_RECHAZO
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_INSERTA_EN_RECL_RECHAZO(P_SOL_SER_ID	NUMBER) IS
		
	V_REC_SECUENCIAL RECLAMO.ID%TYPE;
	V_CODIGO_MENSAJE	VARCHAR2(15);
	V_TEXTO_MENSAJE		VARCHAR2(2000);
	
BEGIN
  P_INSERTA_RECLAMO_RECHAZADO(P_SOL_SER_ID,
  													  V_CODIGO_MENSAJE,
  													  V_TEXTO_MENSAJE,
  													  V_REC_SECUENCIAL);
  
  IF V_REC_SECUENCIAL IS NOT NULL THEN
  	P_BUSCAR_RECLAMO(V_REC_SECUENCIAL, :GLOBAL.COD_COMPANIA);
  END IF;
  
  
END;
