-- PROGRAM UNIT: P_INSERTAR_CORREO
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_INSERTAR_CORREO(P_NUMERO_AFILIADO	VARCHAR2, P_TIPO_AFILIADO VARCHAR2, P_CORREO	VARCHAR2) IS
	R_CORREO CORREO_ELECTRONICO%ROWTYPE;
	V_RESULT	NUMBER;
BEGIN

	R_CORREO.PROPIETARIO := substr(P_NUMERO_AFILIADO,1,7);
	R_CORREO.TIP_PRO := P_TIPO_AFILIADO;
	R_CORREO.TIP_COR := 'C';
	R_CORREO.CORREO := P_CORREO;--:RADICACION.CORREO_NOTIFICA;

	REGISTRAR_CORREO(R_CORREO,V_RESULT);

	IF V_RESULT = 0 THEN
		p_imprime_mensaje(73, NULL);
		RAISE FORM_TRIGGER_FAILURE;	
	END IF;
END;
