-- PROGRAM UNIT: P_INSERTA_EN_RECLAMO
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_INSERTA_EN_RECLAMO(P_SOL_SER_ID NUMBER) IS
		
	V_REC_SECUENCIAL RECLAMO.ID%TYPE;
	V_CODIGO_MENSAJE	VARCHAR2(15);
	V_TEXTO_MENSAJE		VARCHAR2(2000);
	
BEGIN
  P_INSERTA_RECLAMO_APROBADO(P_SOL_SER_ID,
  													 V_CODIGO_MENSAJE,
  													 V_TEXTO_MENSAJE,
  													 V_REC_SECUENCIAL);
  
  IF V_REC_SECUENCIAL IS NOT NULL THEN
  	P_BUSCAR_RECLAMO(V_REC_SECUENCIAL, :GLOBAL.COD_COMPANIA);
  	--:RESUMEN_RECLAMOS.ESTATUS := PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EST_SER_APR_SOL_SER',:GLOBAL.COD_COMPANIA);
  END IF;
  /*
  :system.message_level := 25;
  COMMIT;
  :system.message_level := 0;
  */
  MSG_ALERT('Solicitud '||P_SOL_SER_ID||': '||V_TEXTO_MENSAJE, 'I', false);  -- OMARLIS GOMEZ Y ANGEL CASTILLO, FOREBRA (29/01/2024). DESCOMENTADO
  
  
END;
