-- PROGRAM UNIT: P_LLENAR_BLOQUE_MOTIVO_RECHAZO
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_LLENAR_BLOQUE_MOTIVO_RECHAZO IS
  -- OMARLIS GOMEZ, FOREBRA, (ABRIL,2023). PROGRAMACION DEL BLOQUE
	
	V_MOTIVO_RECHAZO_ID    NUMBER;
	V_DESC_COBERTURA_SALUD VARCHAR2(500);
	V_DESC_MOTIVO_RECHAZO  VARCHAR2(500);	
	V_CONTADOR             NUMBER := 1;
	
	CURSOR CUR_COBERTURA_SOLICITADA IS
	  SELECT ID, COBERTURA_ID 
	    FROM COBERTURA_SOLICITADA 
	  WHERE SOLICITUD_SERVICIO_ID = :RESUMEN_RECLAMOS.ID;
	
	CURSOR CUR_COB_SOL_MOTIVO_RECHAZO(P_COBERTURA_SOLICITADA_ID NUMBER) IS
	  SELECT MOTIVO_RECHAZO_ID 
	    FROM COBERTURA_SOL_MOTIVO_RECHAZO 
	  WHERE COBERTURA_SOLICITADA_ID = P_COBERTURA_SOLICITADA_ID;
	  
	CURSOR CUR_DESC_COBERTURA_SALUD(P_COBERTURA_ID VARCHAR) IS
	  SELECT DESCRIPCION 
	    FROM COBERTURA_SALUD 
	  WHERE CODIGO = P_COBERTURA_ID;
	  
	CURSOR CUR_DESC_MOTIVO_RECHAZO(P_MOTIVO_RECHAZO_ID NUMBER) IS
	  SELECT NOMBRE 
	    FROM MOTIVO_RECHAZO 
	  WHERE ID = P_MOTIVO_RECHAZO_ID;    
	
BEGIN
	set_block_property('MOTIVOS_RECHAZO', INSERT_ALLOWED,PROPERTY_TRUE);
	CLEAR_BLOCK;
	FOR X IN CUR_COBERTURA_SOLICITADA LOOP		
		
		FOR L IN CUR_COB_SOL_MOTIVO_RECHAZO(X.ID) LOOP
		break;
			
			IF V_CONTADOR = 1 THEN
				FIRST_RECORD;
			ELSE	
				NEXT_RECORD;	
			END IF;	
			
			:MOTIVOS_RECHAZO.SOLICITUD_SERVICIO := :RESUMEN_RECLAMOS.ID;		
		  :MOTIVOS_RECHAZO.COBERTURA          := X.COBERTURA_ID;
				
			OPEN  CUR_DESC_COBERTURA_SALUD(X.COBERTURA_ID);
			FETCH CUR_DESC_COBERTURA_SALUD INTO :MOTIVOS_RECHAZO.DESC_COBERTURA;
			CLOSE CUR_DESC_COBERTURA_SALUD;
			
			OPEN  CUR_DESC_MOTIVO_RECHAZO(L.MOTIVO_RECHAZO_ID);
			FETCH CUR_DESC_MOTIVO_RECHAZO INTO :MOTIVOS_RECHAZO.MOTIVO_RECHAZO;
			CLOSE CUR_DESC_MOTIVO_RECHAZO;
						
			V_CONTADOR := V_CONTADOR + 1; 
			
		END LOOP;
		
	END LOOP;	
	
	set_block_property('MOTIVOS_RECHAZO', INSERT_ALLOWED,PROPERTY_FALSE);
	
	GO_ITEM('MOTIVOS_RECHAZO.BTN_VOLVER');
	
END;
