-- PROGRAM UNIT: P_LLENA_CARNET_AFI
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_LLENA_CARNET_AFI(P_ASEGURADO IN NUMBER, P_SECUENCIA IN NUMBER) IS
	CURSOR CUR_CARNET IS
		SELECT NUM_PLA
		FROM AFILIADO_PLASTICOS AP
		WHERE AP.ASEGURADO = P_ASEGURADO
		AND AP.SECUENCIA = P_SECUENCIA
		AND AP.FEC_VER =
		    (SELECT MAX(Z.FEC_VER)
		        FROM AFILIADO_PLASTICOS Z
		     WHERE Z.ASEGURADO = AP.ASEGURADO
		        AND Z.SECUENCIA = AP.SECUENCIA
		        AND (TRUNC(Z.FEC_VER) <= TRUNC(SYSDATE) ))
		AND AP.FEC_U_ACT =
		    (SELECT MAX(Z.FEC_U_ACT) D
		        FROM AFILIADO_PLASTICOS Z
		     WHERE Z.ASEGURADO = AP.ASEGURADO
		        AND Z.SECUENCIA = AP.SECUENCIA
		        AND Z.FEC_VER = AP.FEC_VER)
	union all
			SELECT NUM_PLA
		FROM AFILIADO_PLASTICOS_int AP
		WHERE AP.COD_ASE_LOC  = P_ASEGURADO
		  AND nvl(AP.SEC_DEP_LOC,0)  = P_SECUENCIA
		  AND AP.FEC_VER =
		    (SELECT MAX(Z.FEC_VER)
		        FROM AFILIADO_PLASTICOS_int Z
		     WHERE Z.COD_ASE_LOC = AP.COD_ASE_LOC
		        AND nvl(z.SEC_DEP_LOC,0) = nvl(AP.SEC_DEP_LOC,0)
		        AND (TRUNC(Z.FEC_VER) <= TRUNC(SYSDATE)
		         ))
		        AND AP.FEC_U_ACT =
		    (SELECT MAX(Z.FEC_U_ACT) D
		        FROM AFILIADO_PLASTICOS_int Z
		     WHERE Z.COD_ASE_LOC = AP.COD_ASE_LOC
		        AND nvl(AP.SEC_DEP_LOC,0) = nvl(AP.SEC_DEP_LOC,0)
		        AND Z.FEC_VER = AP.FEC_VER);
        		
BEGIN
  OPEN CUR_CARNET;
  FETCH CUR_CARNET INTO :SOLICITUD_SERVICIO.NUMERO_CARNET;
  CLOSE CUR_CARNET;
END;
