-- PROGRAM UNIT: P_LLENA_TABLAS_TEMPORALES_TABS
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_LLENA_TABLAS_TEMPORALES_TABS IS
BEGIN
  
	declare
		V_NOMBRES						VARCHAR2(500);
		V_APELLIDOS  				VARCHAR2(500);
		V_CED_ACT						VARCHAR2(200);
		V_SEXO							VARCHAR2(100);
		V_ESTATUS						VARCHAR2(100);
		V_CARNET						NUMBER;
		V_ESTADO_PLASTICO		NUMBER;
		V_EDAD							NUMBER;
		V_TIPO							VARCHAR2(100);
		P_ROWS_UPDATED_BP	number;
		P_ROWS_UPDATED_BPD	number;
		P_ROWS_UPDATED_BEL	NUMBER;
		P_ROWS_UPDATED_BEI	NUMBER;
		P_ROWS_UPDATED_BIA	NUMBER;
		P_ROWS_UPDATED_BD		NUMBER;
		P_ROWS_UPDATED_BACP	NUMBER;
		P_ROWS_UPDATED_BT		NUMBER;
		P_ROWS_UPDATED_BC		NUMBER;
		P_ROWS_UPDATED_BL		NUMBER;
	begin
	  
	 REEMBOLSO.PKG_BUSCA_INFO_ASE.P_ELIMINA_TABLAS_TEMPORALES(USER);  -- ELIMINA LA TABLAS TEMPORALES POR USUARIOS
			
	  REEMBOLSO.PKG_BUSCA_INFO_ASE.P_BUSCA_DATOS_ASEG2(:CG$CTRL.ASEGURADO, :CG$CTRL.SECUENCIA_AFI, :CG$CTRL.ASEGURADO,  V_NOMBRES, V_APELLIDOS,       
	  																			V_CED_ACT, 
				                                  V_SEXO,   V_ESTATUS, V_CARNET,  V_ESTADO_PLASTICO, V_EDAD, 
				                                  V_TIPO,   P_ROWS_UPDATED_BIA);  --BUSCA_DATOS_ASEG; 
				                                  
		
		--LCALCANO 1-AGO-23
		IF V_ESTATUS IS NOT NULL THEN
			SET_ITEM_PROPERTY('CG$CTRL.ESTATUS_ASE_POL', VISIBLE, PROPERTY_TRUE);
			:CG$CTRL.ESTATUS_ASE_POL := V_ESTATUS;
		ELSE
			:CG$CTRL.ESTATUS_ASE_POL := NULL;
			SET_ITEM_PROPERTY('CG$CTRL.ESTATUS_ASE_POL', VISIBLE, PROPERTY_TRUE);
		END IF;
		--END
		
		DELETE REEMBOLSO.TEM_PLAN_ASEGURADO WHERE USUARIO = USER;  -- OMARLIS GOMEZ Y ANGEL CASTILLO, FOREBRA (05/02/2024). AGREGA DELETE
    DELETE REEMBOLSO.TEM_PLAN_DENTAL    WHERE USUARIO = USER;  -- OMARLIS GOMEZ Y ANGEL CASTILLO, FOREBRA (05/02/2024). AGREGA DELETE
  
		PKG_BUSCA_INFO_ASE.P_BUSCA_PLANES(:CG$CTRL.ASEGURADO, :CG$CTRL.SECUENCIA_AFI, P_ROWS_UPDATED_BP); --LLENA_PLANES;
		go_block('PLANES');
		execute_query;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_PLANES_DENTALES(P_ROWS_UPDATED_BPD);--LLENA_PLANES_DENTALES;
		go_block('PLAN_DENTAL');
		execute_query;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_ENDOSO_LOCAL(:CG$CTRL.ASEGURADO, :CG$CTRL.SECUENCIA_AFI, P_ROWS_UPDATED_BEL);--LLENA_ENDOSO_LOCAL;
		go_block('ENDOSOS_LOC');
		execute_query;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_ENDOSO_INT(:CG$CTRL.ASEGURADO, P_ROWS_UPDATED_BEI);  --LLENA_ENDOSO_INT;
		go_block('ENDOSOS_INT');
		execute_query;
		
		IF :ENDOSOS_LOC.POLIZA IS NOT NULL OR :ENDOSOS_INT.POLIZA IS NOT NULL  THEN
			SET_ITEM_PROPERTY('CG$CTRL.TIENE_ENDOSO_LBL', VISIBLE, PROPERTY_TRUE);
		ELSE
			SET_ITEM_PROPERTY('CG$CTRL.TIENE_ENDOSO_LBL', VISIBLE, PROPERTY_FALSE);
		END IF;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_DEPENDIENTES(:CG$CTRL.ASEGURADO, P_ROWS_UPDATED_BD);--LLENA_DEPENDIENTES;
		go_block('DEPENDIENTE');
		execute_query;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_AFI_CONTACTO_PREF(V_CARNET, P_ROWS_UPDATED_BACP);--BUSCA_AFI_CONTACTO_PREF;
		go_block('AFILIADO_CONTACTO_PREFERENCIA');
		execute_query;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_TELEFONOS(:CG$CTRL.ASEGURADO, V_CARNET,P_ROWS_UPDATED_BT);--LLENA_TELEFONOS;
		go_block('TELEFONO');
		execute_query;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_CORREOS(:CG$CTRL.ASEGURADO, V_CARNET,P_ROWS_UPDATED_BC); --LLENA_CORREOS;
		go_block('CORREO');
		execute_query;
		
		PKG_BUSCA_INFO_ASE.P_BUSCA_LIMITE_MEDICAMENTOS(V_CARNET); 
		go_block('LIMITES_MEDICAMENTOS');
		execute_query;
		
		 --BUSCA_LIMITE_MEDICAMENTOS; --FOREBRA CAMBIO LA BUSQUEDAD POR CARNET Y
		-- PUSO EL AFILIADO QUE ES POOR DONDE SE BUSCA 15082023
		PKG_BUSCA_INFO_ASE.P_BUSCA_LIMITES(:CG$CTRL.ASEGURADO, :CG$CTRL.NO_AFI, P_ROWS_UPDATED_BL); --BUSCA_LIMITES;
		go_block('LIMITES');
		execute_query;
		
	end;
END;
