-- PROGRAM UNIT: P_LLENA_DATOS_DETALLE
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_LLENA_DATOS_DETALLE IS
	CURSOR C_DATOS_DETALLE IS
		SELECT monto, cantidad, comentario
		 FROM SOLICITUD_PAGO_DETALLE
		WHERE SOLICITUD_PAGO_ID = :RADICACION.NUMERO_SOLICITUD
		;
BEGIN
  OPEN C_DATOS_DETALLE;
  FETCH C_DATOS_DETALLE INTO :SOLICITUD_PAGO_DETALLE.MONTO, 
  													 :SOLICITUD_PAGO_DETALLE.CANTIDAD,
  													 :SOLICITUD_PAGO_DETALLE.OBSERVACION;
	CLOSE C_DATOS_DETALLE;
END;
