-- PROGRAM UNIT: P_MANEJA_HABILITA_COB_ESTATUS
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_MANEJA_HABILITA_COB_ESTATUS(P_HABILITA	VARCHAR2) IS
BEGIN
  IF P_HABILITA = 'S' THEN
  	SET_ITEM_INSTANCE_PROPERTY('SOLICITUD_SERVICIO_DETALLE.COBERTURA_SOL_ESTATUS_ID', CURRENT_RECORD, UPDATE_ALLOWED, PROPERTY_TRUE);
  	SET_ITEM_INSTANCE_PROPERTY('SOLICITUD_SERVICIO_DETALLE.COBERTURA_SOL_ESTATUS_ID', CURRENT_RECORD, INSERT_ALLOWED, PROPERTY_TRUE);
  ELSE
  	SET_ITEM_INSTANCE_PROPERTY('SOLICITUD_SERVICIO_DETALLE.COBERTURA_SOL_ESTATUS_ID', CURRENT_RECORD, UPDATE_ALLOWED, PROPERTY_FALSE);
  	SET_ITEM_INSTANCE_PROPERTY('SOLICITUD_SERVICIO_DETALLE.COBERTURA_SOL_ESTATUS_ID', CURRENT_RECORD, INSERT_ALLOWED, PROPERTY_FALSE);
  END IF;
END;
