-- PROGRAM UNIT: P_MON_CONS_TEMP_IN_UP
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_MON_CONS_TEMP_IN_UP(P_TIPO_COBERTURA NUMBER,P_COBERTURA NUMBER,P_MONTO NUMBER)  

IS

CURSOR CUR_EXISTE IS 
SELECT 1 
FROM REEMBOLSO.MONTO_CONSUMIDO_TEMP
WHERE COBERTURA=P_COBERTURA;


CURSOR CUR_BUSCA_SEC IS
SELECT SEQ_FRECUENCIA_CONSUMIDA_TEMP.NEXTVAL
FROM DUAL;

V_SECUENCIA NUMBER;
V_EXISTE NUMBER;

BEGIN
	
	OPEN CUR_BUSCA_SEC;
	FETCH CUR_BUSCA_SEC INTO V_SECUENCIA;
	CLOSE CUR_BUSCA_SEC;
	
	OPEN CUR_EXISTE;
	FETCH CUR_EXISTE INTO V_EXISTE;
  CLOSE CUR_EXISTE;
		 
	IF V_EXISTE=1 THEN 
		 		UPDATE REEMBOLSO.MONTO_CONSUMIDO_TEMP
			  SET TIPO_COBERTURA=P_TIPO_COBERTURA,MONTO_COBERTURA=NVL(P_MONTO,0)
			  WHERE COBERTURA=P_COBERTURA
			  AND   TIPO_COBERTURA=P_TIPO_COBERTURA;
			  	      --PKG_GENERAL.P_INSERTA_ERROR('P_MON_CONS_TEMP_IN_UP', sqlcode, sqlerrm, 'UPDACOBERTURA:'||P_COBERTURA||'TIPO_COBERTURA'||P_TIPO_COBERTURA||'MONTO'||P_MONTO);
	ELSE 
		 	  		INSERT INTO REEMBOLSO.MONTO_CONSUMIDO_TEMP(TIPO_COBERTURA,MONTO_COBERTURA,COBERTURA,ID)  
			      VALUES (P_TIPO_COBERTURA,NVL(P_MONTO,0) ,P_COBERTURA,V_SECUENCIA);
			      		        
			      
			     -- PKG_GENERAL.P_INSERTA_ERROR('P_MON_CONS_TEMP_IN_UP', sqlcode, sqlerrm, 'INSERTCOBERTURA:'||P_COBERTURA||'TIPO_COBERTURA'||P_TIPO_COBERTURA||'MONTO'||P_MONTO);
	END IF;

	

	
	
  
END;
