-- PROGRAM UNIT: P_VALIDA_PLAN
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_VALIDA_PLAN IS
	CURSOR C_EXISTE(X_PLAN NUMBER) IS
		SELECT DESCRIPCION, COMPANIA, RAMO, SECUENCIAL
		FROM TEMP_PLANES_ASE_REEMB_SERV
		WHERE CODIGO = X_PLAN;
BEGIN
	P_LLENA_TABLA_TMP_PLAN;
			
	OPEN C_EXISTE(:SOLICITUD_SERVICIO.CODIGO_PLAN);
	FETCH C_EXISTE INTO :SOLICITUD_SERVICIO.DSP_PLAN, :SOLICITUD_SERVICIO.COMPANIA, :SOLICITUD_SERVICIO.RAMO, :SOLICITUD_SERVICIO.SECUENCIAL;
	IF C_EXISTE%NOTFOUND THEN
		MSG_ALERT('Este plan no es valido para el asegurado a la fecha de servicio seleccionada.','E',TRUE);
	END IF;
	CLOSE C_EXISTE;
	
	:SOLICITUD_SERVICIO.DSP_INTERMEDIARIO := F_BUSCA_NOMBRE_INTERMED(:SOLICITUD_SERVICIO.COMPANIA, 
																																	 :SOLICITUD_SERVICIO.RAMO, 
																																	 :SOLICITUD_SERVICIO.SECUENCIAL)
																				  	|| ' / '
																 						||F_BUSCA_NOMBRE_GERENTE(:SOLICITUD_SERVICIO.COMPANIA, 
																																	 :SOLICITUD_SERVICIO.RAMO, 
																																	 :SOLICITUD_SERVICIO.SECUENCIAL);
																																	 
	IF :SOLICITUD_SERVICIO.CODIGO_AFILIADO IS NULL THEN
		:SOLICITUD_SERVICIO.CODIGO_AFILIADO := :CG$CTRL.NO_AFI;
		:SOLICITUD_SERVICIO.DSP_AFILIADO := :CG$CTRL.NOMBRE_AFILIADO;
	END IF;																																 
	
	

	
END;
