-- PROGRAM UNIT: P_VALIDA_COB_VACUNA
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_VALIDA_COB_VACUNA IS
	CURSOR C_EDAD(X_ASE NUMBER, X_DEP NUMBER) IS
		SELECT EDAD
		FROM ASE_DEP02_V
		WHERE ASEGURADO = X_ASE
		AND SECUENCIA = X_DEP;
		
	VASE    		NUMBER;
	VDEP    		NUMBER;	
	V_EDAD_AFI	NUMBER;
	V_COB_INFLU	VARCHAR2(100) := PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('COD_COB_VACUNA_INFLU',:GLOBAL.COD_COMPANIA);
	V_EDAD_MAX	NUMBER	:=	TO_NUMBER(PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EDAD_MAX_VACU_INFLU',:GLOBAL.COD_COMPANIA));
		
BEGIN
	IF :SOLICITUD_SERVICIO_DETALLE.COBERTURA = V_COB_INFLU THEN
		VASE:= TO_NUMBER(SUBSTR(NVL(:SOLICITUD_SERVICIO.CODIGO_AFILIADO,:CG$CTRL.NO_AFI),1,7));
		VDEP:= TO_NUMBER(SUBSTR(NVL(:SOLICITUD_SERVICIO.CODIGO_AFILIADO,:CG$CTRL.NO_AFI),8,3));
	
	  OPEN C_EDAD(VASE,VDEP);
	  FETCH C_EDAD INTO V_EDAD_AFI;
	  CLOSE C_EDAD;
	  
	  IF V_EDAD_AFI > V_EDAD_MAX THEN
			:SOLICITUD_SERVICIO_DETALLE.COBERTURA_SOL_ESTATUS_ID := PKG_GENERAL.F_OBTEN_PARAMETRO_SEUS('EST_REC_COB_SOL_REMB',:GLOBAL.COD_COMPANIA);
			:SOLICITUD_SERVICIO_DETALLE.MONTO_PAGAR:=0;
			:SOLICITUD_SERVICIO_DETALLE.MONTO_COASEGURO:=0;
			:SOLICITUD_SERVICIO_DETALLE.MONTO_DIFERENCIA :=:SOLICITUD_SERVICIO_DETALLE.MONTO_TOTAL;	
			--P_MANEJA_HABILITA_COB_ESTATUS('N');
			
			MSG_ALERT('La cobertura no corresponde con la edad '||V_EDAD_AFI||' del Asegurado. Este servicio aplica para un rango de 0 a '||V_EDAD_MAX||' años.','E',false);
		END IF; 	
	END IF;
END;
