-- PROGRAM UNIT: P_VALIDA_ACT_ESTATUS_COB
-- Tipo: Procedure
-- ====================================================================

PROCEDURE P_VALIDA_ACT_ESTATUS_COB IS
BEGIN
  if nvl(:solicitud_servicio_detalle.RECHAZO_AUTOMATICO,'N') = 'S' then
		P_MANEJA_HABILITA_COB_ESTATUS('N');
	ELSIF nvl(:solicitud_servicio_detalle.RECHAZO_AUTOMATICO,'N') = 'N' THEN
		IF :SOLICITUD_SERVICIO_DETALLE.ID IS NULL THEN
			P_MANEJA_HABILITA_COB_ESTATUS('S');
		ELSIF :SOLICITUD_SERVICIO_DETALLE.ID IS NOT NULL THEN
			IF NVL(:SOLICITUD_SERVICIO_DETALLE.MONTO_FREC_EDITADO,'N') = 'S' OR NVL(:SOLICITUD_SERVICIO_DETALLE.HUBO_EXCEPCION,'N') = 'S' THEN
				P_MANEJA_HABILITA_COB_ESTATUS('S');
			ELSE
				P_MANEJA_HABILITA_COB_ESTATUS('N');
			END IF;
		END IF;
	end if;
END;
